import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1764088979463 implements MigrationInterface {
    name = 'Init1764088979463'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "locations" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "placeId" character varying, "address" character varying NOT NULL, "country" character varying, "data" jsonb, "coordinates" geography(Point,4326) NOT NULL, CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_227023051ab1fedef7a3b6c7e2" ON "locations" ("name") `);
        await queryRunner.query(`CREATE INDEX "location_coordinates_idx" ON "locations" USING GiST ("coordinates") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "location_place_id_idx" ON "locations" ("placeId") `);
        await queryRunner.query(`CREATE TYPE "public"."PaymentStatus" AS ENUM('pending', 'completed', 'failed', 'refunded', 'partially_paid', 'hold', 'released')`);
        await queryRunner.query(`CREATE TYPE "public"."PaymentProvider" AS ENUM('stripe')`);
        await queryRunner.query(`CREATE TABLE "payments" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "bookingId" uuid, "amount" numeric(10,2) NOT NULL, "paidAmount" numeric(10,2), "currency" character varying NOT NULL, "holdAmount" integer, "data" jsonb, "status" "public"."PaymentStatus" NOT NULL DEFAULT 'pending', "providerPaymentId" character varying, "providerCustomerId" character varying, "paymentMethodId" character varying, "refundId" character varying, "provider" "public"."PaymentProvider" NOT NULL DEFAULT 'stripe', CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ParticipantStatus" AS ENUM('pending_response', 'pending_payment', 'pending_approval', 'ready', 'entered', 'rejected', 'no_show', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "participants" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "bookingId" uuid NOT NULL, "isCreator" boolean, "status" "public"."ParticipantStatus" NOT NULL, "paymentId" uuid, "cancellationReason" character varying, "rejectionReason" character varying, CONSTRAINT "REL_5cbe8c9d4b4f851e5bfe1cdec4" UNIQUE ("paymentId"), CONSTRAINT "PK_1cda06c31eec1c95b3365a0283f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e5f0aa9fe3a324e00b0b61d6f8" ON "participants" ("bookingId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."AssetType" AS ENUM('profile_picture', 'cover_picture', 'branch_logo', 'branch_cover', 'branch_video', 'court_image', 'court_video', 'post_image', 'post_video', 'tenant_document', 'tenant_logo')`);
        await queryRunner.query(`CREATE TABLE "assets" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fileSize" integer, "mimeType" character varying, "bucket" character varying NOT NULL, "key" character varying NOT NULL, "used" boolean, "resourceId" uuid, "position" integer, "type" "public"."AssetType", "uploadedBy" uuid, CONSTRAINT "UQ_eca5d51e447405fbec6a992c47f" UNIQUE ("key"), CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_asset_resourceId_type" ON "assets" ("resourceId", "type") `);
        await queryRunner.query(`CREATE INDEX "idx_asset_createdAt_used" ON "assets" ("createdAt", "used") `);
        await queryRunner.query(`CREATE TABLE "post_likes" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "idx_post_user" UNIQUE ("postId", "userId"), CONSTRAINT "PK_e4ac7cb9daf243939c6eabb2e0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "posts" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "body" text NOT NULL, "bookingId" uuid, "userId" uuid NOT NULL, "assetId" uuid, "likesCount" integer NOT NULL DEFAULT '0', CONSTRAINT "REL_315bb267deb563eee5bb7d30ec" UNIQUE ("assetId"), CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_post_creatorId" ON "posts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_post_bookingId" ON "posts" ("bookingId") `);
        await queryRunner.query(`CREATE TYPE "public"."BookingEvent" AS ENUM('created', 'started', 'ended', 'participant_entered', 'participant_cancelled', 'participant_removed', 'participant_added', 'participant_joined', 'participant_invitation_accepted', 'participant_invitation_rejected', 'participant_payment_completed', 'participant_join_request_submitted', 'participant_join_request_approved', 'participant_join_request_rejected', 'cancelled', 'moment_posted', 'payment_completed')`);
        await queryRunner.query(`CREATE TABLE "booking_events" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "userId" uuid, "data" jsonb, "event" "public"."BookingEvent" NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "PK_bb7037dff63ec344eba13da5d0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_booking_id_index" ON "booking_events" ("bookingId") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rating" integer NOT NULL, "comment" character varying NOT NULL, "userId" uuid NOT NULL, "bookingId" uuid, CONSTRAINT "idx_review_userId_bookingId" UNIQUE ("userId", "bookingId"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_review_userId" ON "reviews" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."Gender" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."SportLevel" AS ENUM('beginner', 'intermediate', 'intermediate_high', 'advanced', 'competitive')`);
        await queryRunner.query(`CREATE TYPE "public"."PaymentType" AS ENUM('whole', 'split')`);
        await queryRunner.query(`CREATE TYPE "public"."BookingStatus" AS ENUM('cancelled', 'completed', 'in_progress', 'pending')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "staffId" uuid, "courtId" uuid, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "open" boolean NOT NULL DEFAULT false, "duration" integer NOT NULL, "hourlyRate" integer NOT NULL, "gender" "public"."Gender", "level" "public"."SportLevel", "totalAmount" numeric(10,2) NOT NULL, "cancellationReason" character varying, "paymentType" "public"."PaymentType" NOT NULL, "paymentStatus" "public"."PaymentStatus" NOT NULL DEFAULT 'pending', "status" "public"."BookingStatus" NOT NULL DEFAULT 'pending', "playersASide" integer, "autoAccept" boolean, CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_booking_created_at" ON "bookings" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_open" ON "bookings" ("open") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_status_dates" ON "bookings" ("status", "startDate", "endDate") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_court_dates" ON "bookings" ("courtId", "startDate") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_dates" ON "bookings" ("startDate", "endDate") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_status" ON "bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_courtId" ON "bookings" ("courtId") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_userId" ON "bookings" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."StaffRole" AS ENUM('SuperAdmin', 'Admin', 'User')`);
        await queryRunner.query(`CREATE TABLE "staff" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying, "lastName" character varying, "email" character varying, "pendingEmail" character varying, "phoneNumber" character varying, "password" character varying, "verifiedAt" TIMESTAMP, "lastPasswordChangeAt" TIMESTAMP, "tenantId" uuid, "role" "public"."StaffRole" NOT NULL DEFAULT 'SuperAdmin', CONSTRAINT "PK_e4ee98bb552756c180aec1e854a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_staff_phoneNumber" ON "staff" ("phoneNumber") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_staff_email" ON "staff" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_tenant_id" ON "staff" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."StaffInvitationStatus" AS ENUM('pending', 'accepted', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "staff_invitations" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "status" "public"."StaffInvitationStatus" NOT NULL DEFAULT 'pending', "token" character varying NOT NULL, "expires" TIMESTAMP NOT NULL, "role" "public"."StaffRole" NOT NULL DEFAULT 'User', "branchId" uuid, "tenantId" uuid NOT NULL, CONSTRAINT "UQ_4e6e40d4c9c24f41c1067b55140" UNIQUE ("token"), CONSTRAINT "PK_842e5346c92d8003bdb2140b6c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_staff_invitation_token" ON "staff_invitations" ("token") `);
        await queryRunner.query(`CREATE INDEX "idx_staff_invitation_email" ON "staff_invitations" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_staff_invitation_tenant_id" ON "staff_invitations" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "tenants" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "phoneNumber" character varying, "totalCourts" integer, "totalBranches" integer, "totalStaff" integer, "totalBookings" integer, "totalReviews" integer, "totalRevenue" integer, "profileCompletion" jsonb NOT NULL, "ownerId" uuid, "logoAssetId" uuid, CONSTRAINT "REL_dccf2382a3ffe4edfc09b8eeb0" UNIQUE ("ownerId"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availabilities" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "days" integer array NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "scheduleId" uuid NOT NULL, CONSTRAINT "PK_9562bd8681d40361b1a124ea52c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "availability_schedule_idx" ON "availabilities" ("scheduleId") `);
        await queryRunner.query(`CREATE TABLE "schedules" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branchId" uuid, "courtId" uuid, "timeZone" character varying NOT NULL, CONSTRAINT "REL_92233c841da29d74c4ed39e1d9" UNIQUE ("branchId"), CONSTRAINT "REL_f78b3b8cd4922c8011abef1c2e" UNIQUE ("courtId"), CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "schedule_court_idx" ON "schedules" ("courtId") `);
        await queryRunner.query(`CREATE INDEX "schedule_branch_idx" ON "schedules" ("branchId") `);
        await queryRunner.query(`CREATE TYPE "public"."BranchStatus" AS ENUM('open', 'closed', 'occupied', 'under_maintenance')`);
        await queryRunner.query(`CREATE TABLE "branches" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "phoneNumber" character varying NOT NULL, "status" "public"."BranchStatus" NOT NULL, "isVisible" boolean, "tenantId" uuid NOT NULL, "locationId" uuid NOT NULL, "coverUrl" character varying, "logoUrl" character varying, "bookmarksCount" integer NOT NULL DEFAULT '0', "totalBookings" integer NOT NULL DEFAULT '0', "totalOpenBookings" integer NOT NULL DEFAULT '0', "totalRevenue" integer NOT NULL DEFAULT '0', "upcomingBookings" integer NOT NULL DEFAULT '0', "minutesBooked" integer NOT NULL DEFAULT '0', "reviewsCount" integer NOT NULL DEFAULT '0', "avgRating" integer NOT NULL DEFAULT '0', "ratingStats" jsonb NOT NULL DEFAULT '{"1": 0, "2": 0, "3": 0, "4": 0, "5": 0}', "postsCount" integer NOT NULL DEFAULT '0', "courtsCount" integer NOT NULL DEFAULT '0', "deletedAt" TIMESTAMP, CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "branch_location_id_idx" ON "branches" ("locationId") `);
        await queryRunner.query(`CREATE INDEX "branch_status_idx" ON "branches" ("status") `);
        await queryRunner.query(`CREATE INDEX "branch_tenant_id_idx" ON "branches" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."CourtSurface" AS ENUM('grass', 'hard')`);
        await queryRunner.query(`CREATE TYPE "public"."CourtStatus" AS ENUM('available', 'unavailable')`);
        await queryRunner.query(`CREATE TYPE "public"."Sport" AS ENUM('tennis', 'football', 'paddle', 'volleyball')`);
        await queryRunner.query(`CREATE TABLE "courts" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "branchId" uuid NOT NULL, "length" double precision NOT NULL, "width" double precision NOT NULL, "size" character varying NOT NULL, "surface" "public"."CourtSurface" NOT NULL, "status" "public"."CourtStatus" NOT NULL, "avgRating" double precision NOT NULL DEFAULT '0', "reviewsCount" integer NOT NULL DEFAULT '0', "ratingStats" jsonb NOT NULL DEFAULT '{"1": 0, "2": 0, "3": 0, "4": 0, "5": 0}', "locationId" uuid NOT NULL, "hourlyRate" double precision NOT NULL, "sport" "public"."Sport" NOT NULL, "minDuration" integer, "bookmarksCount" integer NOT NULL DEFAULT '0', "totalBookings" integer NOT NULL DEFAULT '0', "totalOpenBookings" integer NOT NULL DEFAULT '0', "totalRevenue" integer NOT NULL DEFAULT '0', "minutesBooked" integer NOT NULL DEFAULT '0', "postsCount" integer NOT NULL DEFAULT '0', "deletedAt" TIMESTAMP, CONSTRAINT "PK_948a5d356c3083f3237ecbf9897" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "court_location_id_idx" ON "courts" ("locationId") `);
        await queryRunner.query(`CREATE INDEX "court_status_idx" ON "courts" ("status") `);
        await queryRunner.query(`CREATE INDEX "court_surface_idx" ON "courts" ("surface") `);
        await queryRunner.query(`CREATE INDEX "court_branch_id_idx" ON "courts" ("branchId") `);
        await queryRunner.query(`CREATE TYPE "public"."BookmarkType" AS ENUM('court', 'user', 'branch')`);
        await queryRunner.query(`CREATE TABLE "bookmarks" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "resourceId" uuid NOT NULL, "type" "public"."BookmarkType" NOT NULL, CONSTRAINT "idx_bookmark_userId_type_resourceId" UNIQUE ("userId", "type", "resourceId"), CONSTRAINT "PK_7f976ef6cecd37a53bd11685f32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying, "lastName" character varying, "email" character varying, "pendingEmail" character varying, "emailVerified" TIMESTAMP, "bio" character varying, "phoneNumber" character varying, "pendingPhoneNumber" character varying, "avatarUrl" character varying, "verifiedAt" TIMESTAMP, "username" character varying, "dateOfBirth" character varying, "gender" "public"."Gender", "firebaseUid" character varying, "stripeCustomerId" character varying, "notificationsCount" integer, "followersCount" integer NOT NULL DEFAULT '0', "followingCount" integer NOT NULL DEFAULT '0', "bookingsCount" integer NOT NULL DEFAULT '0', "minutesBookedCount" integer NOT NULL DEFAULT '0', "reviewsCount" integer NOT NULL DEFAULT '0', "totalSpent" integer NOT NULL DEFAULT '0', "postsCount" integer NOT NULL DEFAULT '0', "deletedAt" TIMESTAMP, CONSTRAINT "idx_user_phoneNumber" UNIQUE ("phoneNumber"), CONSTRAINT "idx_user_email" UNIQUE ("email"), CONSTRAINT "idx_user_username" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."TimePreference" AS ENUM('morning', 'day', 'evening', 'night')`);
        await queryRunner.query(`CREATE TABLE "users_sports" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."Sport" NOT NULL, "level" "public"."SportLevel" NOT NULL, "userId" uuid NOT NULL, "timePreference" "public"."TimePreference" NOT NULL, CONSTRAINT "idx_user_sport_user_id_name" UNIQUE ("userId", "name"), CONSTRAINT "PK_d64ec444cd2023d1676ad92f2d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_sport_user_id" ON "users_sports" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."Language" AS ENUM('en', 'ar')`);
        await queryRunner.query(`CREATE TABLE "user_preferences" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "deviceId" character varying NOT NULL, "notifications" jsonb NOT NULL, "language" "public"."Language" NOT NULL DEFAULT 'en', "currency" character varying NOT NULL DEFAULT 'USD', CONSTRAINT "PK_e8cfb5b31af61cd363a6b6d7c25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5f3603eefe93786a735bd9689e" ON "user_preferences" ("userId", "deviceId") `);
        await queryRunner.query(`CREATE TABLE "branch_staffers" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branchId" uuid NOT NULL, "stafferId" uuid NOT NULL, CONSTRAINT "PK_da25503853ab89e07f9ee861c54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_staffer_id" ON "branch_staffers" ("stafferId") `);
        await queryRunner.query(`CREATE INDEX "idx_branch_id" ON "branch_staffers" ("branchId") `);
        await queryRunner.query(`CREATE TYPE "public"."ReportEntity" AS ENUM('booking', 'user', 'branch', 'court')`);
        await queryRunner.query(`CREATE TYPE "public"."ReportStatus" AS ENUM('pending', 'reviewed', 'resolved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "reports" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reporterId" uuid NOT NULL, "entityId" uuid NOT NULL, "entityType" "public"."ReportEntity" NOT NULL, "reason" character varying NOT NULL, "description" character varying, "status" "public"."ReportStatus" NOT NULL DEFAULT 'pending', CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "addresses" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "street" character varying NOT NULL, "city" character varying NOT NULL, "state" character varying, "country" character varying, "postalCode" character varying, "userId" uuid NOT NULL, CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_address_user_id" ON "addresses" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."NotificationType" AS ENUM('follow', 'booking_cancelled', 'booking_invitation_accepted', 'booking_invitation_rejected', 'booking_reminder', 'booking_invitation', 'booking_entered', 'booking_joined', 'booking_created', 'booking_participant_removed', 'booking_participant_added', 'booking_participant_cancelled', 'booking_started', 'booking_ended', 'booking_join_request_submitted', 'booking_join_request_approved', 'booking_join_request_rejected', 'review_added', 'payment_failed', 'payment_succeeded', 'refund_succeeded', 'refund_failed', 'moment_posted', 'post_like', 'report_created')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."NotificationType" NOT NULL, "userId" uuid NOT NULL, "resourceId" uuid, "count" integer, "data" json NOT NULL, "readAt" TIMESTAMP, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ef19dfa50221762de8ce35b043" ON "notifications" ("userId", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."LogAction" AS ENUM('create', 'update', 'delete')`);
        await queryRunner.query(`CREATE TYPE "public"."UserType" AS ENUM('customer', 'staff')`);
        await queryRunner.query(`CREATE TYPE "public"."LogEntity" AS ENUM('user', 'booking', 'review')`);
        await queryRunner.query(`CREATE TABLE "logs" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "oldSnapshot" jsonb, "newSnapshot" jsonb, "action" "public"."LogAction" NOT NULL, "userId" uuid, "userType" "public"."UserType" NOT NULL, "entity" "public"."LogEntity" NOT NULL, CONSTRAINT "PK_fb1b805f2f7795de79fa69340ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "friendships" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "followerId" uuid NOT NULL, "followingId" uuid NOT NULL, CONSTRAINT "unique_friendship" UNIQUE ("followerId", "followingId"), CONSTRAINT "unique_friendship_followingId_followerId" UNIQUE ("followingId", "followerId"), CONSTRAINT "PK_08af97d0be72942681757f07bc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_friendship_followingId_createdAt" ON "friendships" ("followingId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_friendship_followerId_createdAt" ON "friendships" ("followerId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_friendship_created" ON "friendships" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_friendship_followingId" ON "friendships" ("followingId") `);
        await queryRunner.query(`CREATE INDEX "idx_friendship_followerId" ON "friendships" ("followerId") `);
        await queryRunner.query(`CREATE TYPE "public"."VerificationChannel" AS ENUM('email', 'phone')`);
        await queryRunner.query(`CREATE TYPE "public"."VerificationContext" AS ENUM('account_verification', 'password_reset', 'email_verification')`);
        await queryRunner.query(`CREATE TABLE "verifications" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "identifier" character varying NOT NULL, "value" character varying NOT NULL, "channel" "public"."VerificationChannel" NOT NULL, "context" "public"."VerificationContext" NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP NOT NULL, CONSTRAINT "idx_verification_context" UNIQUE ("userId", "context"), CONSTRAINT "PK_2127ad1b143cf012280390b01d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_verification_identifier" ON "verifications" ("identifier") `);
        await queryRunner.query(`CREATE TYPE "public"."AccountProvider" AS ENUM('email', 'phone', 'google', 'apple')`);
        await queryRunner.query(`CREATE TABLE "accounts" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "provider" "public"."AccountProvider" NOT NULL, CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_account_userId" ON "accounts" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."SessionStatus" AS ENUM('active', 'revoked', 'expired')`);
        await queryRunner.query(`CREATE TABLE "sessions" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "refreshToken" character varying NOT NULL, "ip" character varying, "userAgent" character varying, "status" "public"."SessionStatus" NOT NULL DEFAULT 'active', "language" "public"."Language", "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "userId" uuid NOT NULL, "fcmToken" character varying, "deviceId" character varying, CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_session_userId" ON "sessions" ("userId") `);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_5fc9cddc801b973cd9edcdda42a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_b9792fd8f201c7f5a1be3ce5c36" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_5cbe8c9d4b4f851e5bfe1cdec43" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_6999d13aca25e33515210abaf16" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_d0c455d2cc7debb1bcbc1b67189" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_ae05faaa55c866130abef6e1fee" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_315bb267deb563eee5bb7d30ecc" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_events" ADD CONSTRAINT "FK_d49ecfcfd991d884a03e8488e32" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_events" ADD CONSTRAINT "FK_4d99c5eaf62ad900cd0257bc550" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c357057587a1c2afae453515bf6" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_38a69a58a323647f2e75eb994de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_c3e05cfa3bde93838eb75565326" FOREIGN KEY ("staffId") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_e8e9a995f2078e6c39793a7f16b" FOREIGN KEY ("courtId") REFERENCES "courts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_c4f42a7776a2fd07edf070e3953" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ADD CONSTRAINT "FK_5e30a5ac7c706ddec1a5e2b1b71" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ADD CONSTRAINT "FK_b3ca8df9ca2b559bdbfff07a052" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_582c8ca5244a062f2cae49de545" FOREIGN KEY ("logoAssetId") REFERENCES "assets"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_dccf2382a3ffe4edfc09b8eeb06" FOREIGN KEY ("ownerId") REFERENCES "staff"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availabilities" ADD CONSTRAINT "FK_6911e4f74fb694db7272db7b450" FOREIGN KEY ("scheduleId") REFERENCES "schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_92233c841da29d74c4ed39e1d90" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_f78b3b8cd4922c8011abef1c2e6" FOREIGN KEY ("courtId") REFERENCES "courts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_77726af97a595fe5b8c071cf6c7" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_19db6a12993aa421cc984376635" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courts" ADD CONSTRAINT "FK_fd42d809b0572491ee0097396fe" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courts" ADD CONSTRAINT "FK_11f510a5c5ab6cd7197e01b0ef7" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmarks" ADD CONSTRAINT "FK_c6065536f2f6de3a0163e19a584" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_sports" ADD CONSTRAINT "FK_ce700e6036b9eaa97494bac2cd7" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staffers" ADD CONSTRAINT "FK_d772db841d875a2e7e617d6c53e" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staffers" ADD CONSTRAINT "FK_4533af12fe318cf3d7ed7525dd9" FOREIGN KEY ("stafferId") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_7f2424fa59075b5de97d282f8ec" FOREIGN KEY ("followerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_116d0f941d5ffdffbe5da1110f7" FOREIGN KEY ("followingId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_116d0f941d5ffdffbe5da1110f7"`);
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_7f2424fa59075b5de97d282f8ec"`);
        await queryRunner.query(`ALTER TABLE "branch_staffers" DROP CONSTRAINT "FK_4533af12fe318cf3d7ed7525dd9"`);
        await queryRunner.query(`ALTER TABLE "branch_staffers" DROP CONSTRAINT "FK_d772db841d875a2e7e617d6c53e"`);
        await queryRunner.query(`ALTER TABLE "users_sports" DROP CONSTRAINT "FK_ce700e6036b9eaa97494bac2cd7"`);
        await queryRunner.query(`ALTER TABLE "bookmarks" DROP CONSTRAINT "FK_c6065536f2f6de3a0163e19a584"`);
        await queryRunner.query(`ALTER TABLE "courts" DROP CONSTRAINT "FK_11f510a5c5ab6cd7197e01b0ef7"`);
        await queryRunner.query(`ALTER TABLE "courts" DROP CONSTRAINT "FK_fd42d809b0572491ee0097396fe"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_19db6a12993aa421cc984376635"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_77726af97a595fe5b8c071cf6c7"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_f78b3b8cd4922c8011abef1c2e6"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_92233c841da29d74c4ed39e1d90"`);
        await queryRunner.query(`ALTER TABLE "availabilities" DROP CONSTRAINT "FK_6911e4f74fb694db7272db7b450"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_dccf2382a3ffe4edfc09b8eeb06"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_582c8ca5244a062f2cae49de545"`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" DROP CONSTRAINT "FK_b3ca8df9ca2b559bdbfff07a052"`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" DROP CONSTRAINT "FK_5e30a5ac7c706ddec1a5e2b1b71"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_c4f42a7776a2fd07edf070e3953"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_e8e9a995f2078e6c39793a7f16b"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_c3e05cfa3bde93838eb75565326"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_38a69a58a323647f2e75eb994de"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c357057587a1c2afae453515bf6"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f"`);
        await queryRunner.query(`ALTER TABLE "booking_events" DROP CONSTRAINT "FK_4d99c5eaf62ad900cd0257bc550"`);
        await queryRunner.query(`ALTER TABLE "booking_events" DROP CONSTRAINT "FK_d49ecfcfd991d884a03e8488e32"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_315bb267deb563eee5bb7d30ecc"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_ae05faaa55c866130abef6e1fee"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_d0c455d2cc7debb1bcbc1b67189"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_6999d13aca25e33515210abaf16"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_5cbe8c9d4b4f851e5bfe1cdec43"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_b9792fd8f201c7f5a1be3ce5c36"`);
        await queryRunner.query(`ALTER TABLE "participants" DROP CONSTRAINT "FK_5fc9cddc801b973cd9edcdda42a"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1"`);
        await queryRunner.query(`DROP INDEX "public"."idx_session_userId"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TYPE "public"."SessionStatus"`);
        await queryRunner.query(`DROP INDEX "public"."idx_account_userId"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TYPE "public"."AccountProvider"`);
        await queryRunner.query(`DROP INDEX "public"."idx_verification_identifier"`);
        await queryRunner.query(`DROP TABLE "verifications"`);
        await queryRunner.query(`DROP TYPE "public"."VerificationContext"`);
        await queryRunner.query(`DROP TYPE "public"."VerificationChannel"`);
        await queryRunner.query(`DROP INDEX "public"."idx_friendship_followerId"`);
        await queryRunner.query(`DROP INDEX "public"."idx_friendship_followingId"`);
        await queryRunner.query(`DROP INDEX "public"."idx_friendship_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_friendship_followerId_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."idx_friendship_followingId_createdAt"`);
        await queryRunner.query(`DROP TABLE "friendships"`);
        await queryRunner.query(`DROP TABLE "logs"`);
        await queryRunner.query(`DROP TYPE "public"."LogEntity"`);
        await queryRunner.query(`DROP TYPE "public"."UserType"`);
        await queryRunner.query(`DROP TYPE "public"."LogAction"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef19dfa50221762de8ce35b043"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."NotificationType"`);
        await queryRunner.query(`DROP INDEX "public"."idx_address_user_id"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."ReportStatus"`);
        await queryRunner.query(`DROP TYPE "public"."ReportEntity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_staffer_id"`);
        await queryRunner.query(`DROP TABLE "branch_staffers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f3603eefe93786a735bd9689e"`);
        await queryRunner.query(`DROP TABLE "user_preferences"`);
        await queryRunner.query(`DROP TYPE "public"."Language"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_sport_user_id"`);
        await queryRunner.query(`DROP TABLE "users_sports"`);
        await queryRunner.query(`DROP TYPE "public"."TimePreference"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "bookmarks"`);
        await queryRunner.query(`DROP TYPE "public"."BookmarkType"`);
        await queryRunner.query(`DROP INDEX "public"."court_branch_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."court_surface_idx"`);
        await queryRunner.query(`DROP INDEX "public"."court_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."court_location_id_idx"`);
        await queryRunner.query(`DROP TABLE "courts"`);
        await queryRunner.query(`DROP TYPE "public"."Sport"`);
        await queryRunner.query(`DROP TYPE "public"."CourtStatus"`);
        await queryRunner.query(`DROP TYPE "public"."CourtSurface"`);
        await queryRunner.query(`DROP INDEX "public"."branch_tenant_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."branch_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."branch_location_id_idx"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP TYPE "public"."BranchStatus"`);
        await queryRunner.query(`DROP INDEX "public"."schedule_branch_idx"`);
        await queryRunner.query(`DROP INDEX "public"."schedule_court_idx"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP INDEX "public"."availability_schedule_idx"`);
        await queryRunner.query(`DROP TABLE "availabilities"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP INDEX "public"."idx_staff_invitation_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_staff_invitation_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_staff_invitation_token"`);
        await queryRunner.query(`DROP TABLE "staff_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."StaffInvitationStatus"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_staff_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_staff_phoneNumber"`);
        await queryRunner.query(`DROP TABLE "staff"`);
        await queryRunner.query(`DROP TYPE "public"."StaffRole"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_userId"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_courtId"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_dates"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_court_dates"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_status_dates"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_open"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_created_at"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."BookingStatus"`);
        await queryRunner.query(`DROP TYPE "public"."PaymentType"`);
        await queryRunner.query(`DROP TYPE "public"."SportLevel"`);
        await queryRunner.query(`DROP TYPE "public"."Gender"`);
        await queryRunner.query(`DROP INDEX "public"."idx_review_userId"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_id_index"`);
        await queryRunner.query(`DROP TABLE "booking_events"`);
        await queryRunner.query(`DROP TYPE "public"."BookingEvent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_post_bookingId"`);
        await queryRunner.query(`DROP INDEX "public"."idx_post_creatorId"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TABLE "post_likes"`);
        await queryRunner.query(`DROP INDEX "public"."idx_asset_createdAt_used"`);
        await queryRunner.query(`DROP INDEX "public"."idx_asset_resourceId_type"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TYPE "public"."AssetType"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5f0aa9fe3a324e00b0b61d6f8"`);
        await queryRunner.query(`DROP TABLE "participants"`);
        await queryRunner.query(`DROP TYPE "public"."ParticipantStatus"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."PaymentProvider"`);
        await queryRunner.query(`DROP TYPE "public"."PaymentStatus"`);
        await queryRunner.query(`DROP INDEX "public"."location_place_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."location_coordinates_idx"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_227023051ab1fedef7a3b6c7e2"`);
        await queryRunner.query(`DROP TABLE "locations"`);
    }

}
