export const timeZones = [
  { label: "(UTC-12:00) Baker Island Time", value: "Pacific/Baker" },
  { label: "(UTC-11:00) Niue Time", value: "Pacific/Niue" },
  {
    label: "(UTC-10:00) Hawaii-Aleutian Standard Time",
    value: "Pacific/Honolulu",
  },
  { label: "(UTC-09:30) Marquesas Islands Time", value: "Pacific/Marquesas" },
  { label: "(UTC-09:00) Alaska Standard Time", value: "America/Anchorage" },
  { label: "(UTC-08:00) Pacific Standard Time", value: "America/Los_Angeles" },
  { label: "(UTC-07:00) Mountain Standard Time", value: "America/Denver" },
  { label: "(UTC-06:00) Central Standard Time", value: "America/Chicago" },
  { label: "(UTC-05:00) Eastern Standard Time", value: "America/New_York" },
  { label: "(UTC-04:00) Atlantic Standard Time", value: "America/Halifax" },
  {
    label: "(UTC-03:30) Newfoundland Standard Time",
    value: "America/St_Johns",
  },
  {
    label: "(UTC-03:00) Argentina, Brazil Time",
    value: "America/Argentina/Buenos_Aires",
  },
  {
    label: "(UTC-02:00) South Georgia/Sandwich Islands",
    value: "Atlantic/South_Georgia",
  },
  { label: "(UTC-01:00) Azores Standard Time", value: "Atlantic/Azores" },
  { label: "(UTC+00:00) Greenwich Mean Time", value: "Etc/UTC" },
  { label: "(UTC+01:00) Central European Time", value: "Europe/Berlin" },
  { label: "(UTC+02:00) Eastern European Time", value: "Europe/Athens" },
  { label: "(UTC+03:00) Arabia Standard Time", value: "Asia/Riyadh" },
  { label: "(UTC+03:30) Iran Standard Time", value: "Asia/Tehran" },
  { label: "(UTC+04:00) Gulf Standard Time", value: "Asia/Dubai" },
  { label: "(UTC+04:30) Afghanistan Time", value: "Asia/Kabul" },
  { label: "(UTC+05:00) Pakistan Standard Time", value: "Asia/Karachi" },
  { label: "(UTC+05:30) India Standard Time", value: "Asia/Kolkata" },
  { label: "(UTC+06:00) Bangladesh Standard Time", value: "Asia/Dhaka" },
  { label: "(UTC+07:00) Indochina Time", value: "Asia/Bangkok" },
  { label: "(UTC+08:00) China Standard Time", value: "Asia/Shanghai" },
  { label: "(UTC+09:00) Japan Standard Time", value: "Asia/Tokyo" },
  { label: "(UTC+09:30) Australian Central Time", value: "Australia/Adelaide" },
  { label: "(UTC+10:00) Australian Eastern Time", value: "Australia/Sydney" },
  { label: "(UTC+11:00) Solomon Islands Time", value: "Pacific/Guadalcanal" },
  { label: "(UTC+12:00) New Zealand Standard Time", value: "Pacific/Auckland" },
  { label: "(UTC+13:00) Samoa Time", value: "Pacific/Apia" },
  { label: "(UTC+14:00) Line Islands Time", value: "Pacific/Kiritimati" },
];

export const daysOfWeek = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
