export type querykeysType = keyof typeof queryKeys;
export const queryKeys = {
  getUserLocation: "getUserLocation",
  getProfile: "getProfile",
  getCourtDetails: "getCourtDetails",
  getCourts: "getCourts",
  getHomeCourts: "getHomeCourts",
  getBranchById: "getBranchById",
  getMyBookmarks: "getMyBookmarks",
  getBookingTimeSlots: "getBookingTimeSlots",
  getFriendships: "getFriendships",
  getNotifications: "getNotifications",
  getNotificationsSettings: "getNotificationsSettings",
  getCurrentBookings: "getCurrentBookings",
  getHistoryBookings: "getHistoryBookings",
  getActivityLogs: "getActivityLogs",
  getSearchCourts: "getSearchCourts",
  getUsers: "getUsers",
  getOpenMatches: "getOpenMatches",
  getOpenMatchTimeSlots: "getOpenMatchTimeSlots",
  getCourtReviews: "getCourtReviews",
  getPosts: "getPosts",
  getMatchById: "getMatchById",
  getBookings: "getBookings",
  getOpenBookings: "getOpenBookings",
  getBookingEvents: "getBookingEvents",
  getUserById: "getUserById",
};
