import type { ThemeConfig } from "antd";

export const COLORS = {
  ink: "#0A1517",
  deep: "#142326",
  lime: "#C0FF42",
  limeHover: "#B5F536",
  limeActive: "#A6E62A",
  ground: "#F3F5F4",
  card: "#FFFFFF",
  line: "#E4E9E8",
  lineStrong: "#C9D3D2",
  divider: "#EEF1F0",
  muted: "#627174",
  faint: "#9AA6A8",
  limeTint: "#EEF9D4",
  limeTintText: "#2F4A08",
  limeWash: "#F7FBEC",
  rowHover: "#F7F9F8",
  successBg: "#E6F6EE",
  success: "#0B6B3D",
  warningBg: "#FFF6DC",
  warning: "#7A5300",
  danger: "#D92D20",
  dangerBg: "#FEECEB",
  dangerText: "#B42318",
  star: "#E8A400",
  onInkMuted: "#AEBBBD",
  sidebarText: "#C8D3D4",
} as const;

export const FONT_TEXT = "'Readex Pro', system-ui, -apple-system, 'Segoe UI', sans-serif";

const SHADOW_POPUP = "0 2px 6px rgba(10, 21, 23, 0.06), 0 14px 36px rgba(10, 21, 23, 0.14)";

const FOCUS_GLOW = "0 0 0 3px rgba(192, 255, 66, 0.55)";

const fieldTokens = {
  activeBorderColor: COLORS.ink,
  hoverBorderColor: COLORS.lineStrong,
  activeShadow: FOCUS_GLOW,
  borderRadius: 14,
  borderRadiusLG: 14,
  borderRadiusSM: 10,
};

// Selection, focus and links use ink so lime never lands as text on white;
// lime is the primary button fill (ink label) and the active sidebar item.
export const theme: ThemeConfig = {
  token: {
    colorPrimary: COLORS.ink,
    colorInfo: COLORS.ink,
    colorSuccess: COLORS.success,
    colorWarning: COLORS.star,
    colorError: COLORS.danger,
    colorLink: COLORS.ink,
    colorLinkHover: COLORS.deep,
    colorLinkActive: COLORS.ink,
    colorText: COLORS.ink,
    colorTextHeading: COLORS.ink,
    colorTextSecondary: COLORS.muted,
    colorTextDescription: COLORS.muted,
    colorTextTertiary: COLORS.muted,
    colorTextPlaceholder: COLORS.faint,
    colorTextDisabled: COLORS.faint,
    colorBorder: COLORS.line,
    colorBorderSecondary: COLORS.divider,
    colorSplit: COLORS.divider,
    colorBgLayout: COLORS.ground,
    colorBgContainer: COLORS.card,
    colorBgElevated: COLORS.card,
    controlItemBgHover: COLORS.ground,
    controlItemBgActive: COLORS.limeTint,
    controlItemBgActiveHover: "#E6F5C2",
    fontFamily: FONT_TEXT,
    fontSize: 14,
    fontWeightStrong: 600,
    borderRadius: 12,
    borderRadiusLG: 22,
    borderRadiusSM: 10,
    borderRadiusXS: 6,
    controlHeight: 44,
    colorBgMask: "rgba(10, 21, 23, 0.45)",
    boxShadowSecondary: SHADOW_POPUP,
    motionDurationFast: "0.12s",
    motionDurationMid: "0.18s",
    motionDurationSlow: "0.22s",
    // antd's own drawer/modal/dropdown animations; the CSS ones are handled
    // by the prefers-reduced-motion block in index.css.
    motion:
      typeof window === "undefined" ||
      !window.matchMedia("(prefers-reduced-motion: reduce)").matches,
  },
  components: {
    Layout: {
      siderBg: COLORS.ink,
      bodyBg: COLORS.ground,
      headerBg: "transparent",
      headerColor: COLORS.ink,
      headerHeight: 76,
      headerPadding: "0 clamp(16px, 3vw, 40px)",
      triggerBg: COLORS.deep,
    },
    Menu: {
      darkItemBg: COLORS.ink,
      darkSubMenuItemBg: COLORS.ink,
      darkPopupBg: COLORS.ink,
      darkItemColor: COLORS.sidebarText,
      darkItemHoverColor: "#FFFFFF",
      darkItemHoverBg: "rgba(255, 255, 255, 0.06)",
      darkItemSelectedBg: COLORS.lime,
      darkItemSelectedColor: COLORS.ink,
      itemSelectedBg: COLORS.limeTint,
      itemSelectedColor: COLORS.ink,
      itemHoverBg: COLORS.ground,
      itemHeight: 44,
      itemBorderRadius: 12,
      itemMarginInline: 0,
      itemMarginBlock: 4,
      iconSize: 17,
      iconMarginInlineEnd: 12,
      activeBarBorderWidth: 0,
    },
    Button: {
      colorPrimary: COLORS.lime,
      colorPrimaryHover: COLORS.limeHover,
      colorPrimaryActive: COLORS.limeActive,
      primaryColor: COLORS.ink,
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      defaultBg: COLORS.card,
      defaultColor: COLORS.ink,
      defaultBorderColor: COLORS.line,
      defaultHoverBg: COLORS.card,
      defaultHoverColor: COLORS.ink,
      defaultHoverBorderColor: COLORS.ink,
      defaultActiveBg: COLORS.ground,
      defaultActiveColor: COLORS.ink,
      defaultActiveBorderColor: COLORS.ink,
      colorLink: COLORS.ink,
      colorLinkHover: COLORS.deep,
      colorLinkActive: COLORS.ink,
      textHoverBg: "rgba(10, 21, 23, 0.06)",
      fontWeight: 600,
      borderRadius: 999,
      borderRadiusLG: 999,
      borderRadiusSM: 999,
      paddingInline: 20,
      paddingInlineLG: 26,
      paddingInlineSM: 12,
      controlHeightLG: 52,
      contentFontSizeLG: 15,
    },
    Input: { ...fieldTokens, paddingInline: 14, controlHeightLG: 50 },
    InputNumber: { ...fieldTokens, controlHeightLG: 50 },
    DatePicker: {
      ...fieldTokens,
      controlHeightLG: 50,
      cellHoverBg: COLORS.ground,
      cellActiveWithRangeBg: COLORS.limeTint,
    },
    Select: {
      activeBorderColor: COLORS.ink,
      hoverBorderColor: COLORS.lineStrong,
      activeOutlineColor: "rgba(192, 255, 66, 0.55)",
      optionSelectedBg: COLORS.limeTint,
      optionSelectedColor: COLORS.ink,
      optionSelectedFontWeight: 600,
      optionActiveBg: COLORS.ground,
      optionPadding: "8px 12px",
      borderRadius: 14,
      borderRadiusLG: 14,
      borderRadiusSM: 10,
      controlHeightLG: 50,
    },
    Card: {
      headerBg: "transparent",
      headerFontSize: 14,
      headerHeight: 60,
      headerPadding: 22,
      bodyPadding: 22,
      colorBorderSecondary: "transparent",
    },
    Table: {
      headerBg: COLORS.card,
      headerColor: COLORS.muted,
      headerSplitColor: "transparent",
      headerSortActiveBg: COLORS.card,
      headerSortHoverBg: COLORS.rowHover,
      bodySortBg: "#FBFCFC",
      borderColor: COLORS.divider,
      rowHoverBg: COLORS.rowHover,
      rowSelectedBg: COLORS.limeWash,
      rowSelectedHoverBg: "#F1F8E0",
      rowExpandedBg: COLORS.ground,
      cellPaddingBlock: 14,
      cellPaddingInline: 12,
      headerBorderRadius: 22,
    },
    Pagination: {
      itemActiveBg: COLORS.ink,
      itemActiveColor: "#FFFFFF",
      itemActiveColorHover: "#FFFFFF",
      itemBg: "transparent",
      itemSize: 40,
      itemSizeSM: 30,
      borderRadius: 999,
    },
    Tabs: {
      inkBarColor: COLORS.ink,
      itemColor: COLORS.muted,
      itemHoverColor: COLORS.ink,
      itemActiveColor: COLORS.ink,
      itemSelectedColor: COLORS.ink,
      titleFontSize: 14,
      horizontalItemGutter: 28,
      horizontalMargin: "0 0 20px 0",
    },
    Segmented: {
      trackBg: COLORS.card,
      trackPadding: 4,
      itemColor: COLORS.muted,
      itemHoverColor: COLORS.ink,
      itemHoverBg: COLORS.ground,
      itemActiveBg: COLORS.divider,
      itemSelectedBg: COLORS.ink,
      itemSelectedColor: "#FFFFFF",
      controlHeight: 46,
      borderRadius: 999,
      borderRadiusSM: 999,
      borderRadiusLG: 999,
      borderRadiusXS: 999,
    },
    Tag: {
      defaultBg: COLORS.card,
      defaultColor: COLORS.ink,
      borderRadiusSM: 999,
    },
    Badge: {
      indicatorHeight: 18,
      indicatorHeightSM: 16,
      textFontWeight: 700,
    },
    Modal: {
      titleFontSize: 18,
      borderRadiusLG: 22,
    },
    Popover: {
      borderRadiusLG: 18,
    },
    Dropdown: {
      borderRadiusLG: 14,
      borderRadiusSM: 10,
      paddingBlock: 8,
    },
    Descriptions: {
      labelBg: COLORS.ground,
      labelColor: COLORS.muted,
      contentColor: COLORS.ink,
      titleColor: COLORS.ink,
      borderRadiusLG: 14,
    },
    Statistic: {
      titleFontSize: 13,
      contentFontSize: 30,
    },
    Form: {
      labelColor: COLORS.ink,
      labelFontSize: 13,
      verticalLabelPadding: "0 0 6px",
      itemMarginBottom: 20,
    },
    Alert: {
      borderRadiusLG: 14,
    },
    Drawer: {
      footerPaddingBlock: 16,
      footerPaddingInline: 24,
    },
  },
};
