export const BOOKING = {
  MINUTES_PER_HOUR: 60,
  MIN_DURATION_MINUTES: 30,

  MAX_PARTICIPANTS_PER_BOOKING: 4,
  MIN_PLAYERS_PER_SIDE: 1,
  MAX_PLAYERS_PER_SIDE: 2,
  SRID_WGS84: 4326,
  SLOT_RESERVATION_TTL_SECONDS: 600,
} as const;

export const REMINDER_INTERVALS = {
  HOUR: 60,
  HALF_HOUR: 30,
  QUARTER_HOUR: 15,
} as const;
